### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by rshingavi97** [maxchk/grad#1]
I am beginner for ruby and wanted to use this excellent tool to process the log file around 15GB according to our requirement.

We have tried to build by performing following steps:
[Assume downloaded this repository from git hub & installed ruby 1.9.3]

Step:  inside /grad/lib directory, provide command as  ruby grad.rb

But it is not showing any output or any information.
Even we tried to execute /grad/bin/grad file also but nothing happened.

I request you to let me know how to build this if required or how to use this tool.

**Comment by rshingavi97** [comment]
I have resolved the issues and got to know how to start and use this.

Kindly address, Can we replay a log file of at least 15GB by using this tool. 

According to our requirement , we have to update the Time-stamp  of every log.
Hence let me know which switch should we use to replace existing string from the file.

**Comment by maxchk** [comment]
> I have resolved the issues and got to know how to start and use this.

Great. I'll still probably provide some install HOWTO, just to save on time for other people with non ruby background :)

> Can we replay a log file of at least 15GB by using this tool.

I didn't test anything larger than 0,5GB but 15GB should work.
At least Grad's only limit is a hardware where it runs.
At first I would suggest to start with small log and see how it runs before feeding 15GB log to it.
Please let me know if you have any issues. 

> replace existing string from the file.

Grad doesn't modify original log.
It reads a very first entry from the log and sets it to 'now'.
After that all subsequent entries are played relative to the first one.
So, if you have 3 entries in your log with following times:
09/Dec/2013:09:40:01 - line1
09/Dec/2013:09:40:31 - line2
09/Dec/2013:09:41:31 - line3
Grad will play line1 as soon as you start it.
Line2 in 30 seconds and line3 in 60 seconds from the start.
Please let me know if this answers your question.
